### ISSUE TITLE
Calendar/time component for start/end input

### ISSUE THREAD

**Issue by AntoineTurmel** [anvaka/time#3]
A calendar component would be nice to choose day/time instead of just text input.
Anyway, it's a cool tool !

**Comment by anvaka** [comment]
@AntoineTurmel Thank you! I'm using [`datetime-local`](https://www.w3.org/TR/html-markup/input.datetime-local.html) input field, which is apparently not supported by Firefox (http://caniuse.com/#search=datetime ). Do you use Firefox too?

**Comment by AntoineTurmel** [comment]
Yeah there are still people who use Firefox ;)

**Comment by PaulBGD** [comment]
Here's a polyfill for the datetime-local feature: https://github.com/zoltan-dulac/html5Forms.js

**Comment by anvaka** [comment]
@AntoineTurmel I love Firefox :). I just prefer to log everything from my mobile phone.

I just integrated [flatpickr](https://chmln.github.io/flatpickr/) - hope this helps!
