### ISSUE TITLE
run project

### ISSUE THREAD

**Issue by tsvetkovpro** [anvaka/time#5]
good day. follow your instruction and got error:

git clone https://github.com/anvaka/time.git
cd time
npm install
npm run dev

![image](https://cloud.githubusercontent.com/assets/2004857/19184179/55dbf3bc-8c95-11e6-8162-e53788fd8189.png)

my config:

![image](https://cloud.githubusercontent.com/assets/2004857/19184229/988b2f98-8c95-11e6-8edb-2f10c069d971.png)

![image](https://cloud.githubusercontent.com/assets/2004857/19184280/c9166b32-8c95-11e6-86f9-ec0a12de8fda.png)

**Comment by anvaka** [comment]
Did you have any errors during `npm install`? How do you access that page? Seems like for some reason it is not built correctly...
