### ISSUE TITLE
Different origin

### ISSUE THREAD

**Issue by yong86** [anvaka/time#8]
Hello,
Thanks for sharing it.I hosted this application on a server ,but I got the below two issues while trying to access it from a different client

![error](https://user-images.githubusercontent.com/7461579/30035543-8ca31a94-91ab-11e7-95da-7cc7e3af6e50.PNG).

**Comment by yong86** [comment]
Sorry, solved it by creating own client ID

**Comment by anvaka** [comment]
Yup!
